---
title: "Dr. Semmelweis and the Importance of Handwashing"
author: "Elvin Abdullayev"
date: "03-02-2024"
output:
  pdf_document: default
  html_document: default
---

# 1. Loading data

```{r}
library(tidyverse)

yearly <- read_csv("yearly_deaths_by_clinic.csv")
monthly <- read_csv("monthly_deaths.csv")

print(yearly)
print(monthly)
```

# 2. Add new column

```{r}
yearly <- yearly %>%
mutate(proportion_deaths = deaths / births)

monthly <- monthly %>%
mutate(proportion_deaths = deaths / births)

print(yearly)
print(monthly)
```

# 3. Make a line plot

```{r}
ggplot(yearly, aes(x = year, y = proportion_deaths, color = clinic)) + geom_line()
ggplot(monthly, aes(date, proportion_deaths)) + geom_line() + labs(x = "Year", y = "Proportion Deaths")
```

# 4. Add the threshold and flag and plot again

```{r}
handwashing_start = as.Date('1847-06-01')

monthly <- monthly %>%
mutate(handwashing_started = date >= handwashing_start)

ggplot(monthly, aes(x = date, y = proportion_deaths, color = handwashing_started)) + geom_line()
```
# 5. Find the mean

```{r}

monthly_summary <- monthly %>% 
  group_by(handwashing_started) %>%
  summarize(mean_proportion_deaths = mean(proportion_deaths))

monthly_summary
```
